#!/usr/bin/env python3
"""Turn a Natural Earth land outline into one SVG path, for `web/src/world.ts`.

    python scripts/worldmap.py ne_110m_land.geojson web/src/world.ts

# Why a bundled outline and not map tiles

Tiles come from a tile server. This product is deployed on-premise and often air-gapped —
`crates/uops-oui` makes the same argument about the IEEE registry — so a map that fetched
tiles would be a blank grey rectangle for exactly the customers most likely to have forty
sites across a country. It would also send every viewer's map extent to a third party,
which is a data-protection conversation nobody wants to have about a status board.

The cost is that this is a *locator* map: coastlines, no roads, no labels, no zoom into a
street. For "which of my forty sites is red" that is the whole requirement.

# Why equirectangular

Because the output is an SVG path in a 360x180 box and longitude/latitude map to x/y with
one subtraction each, which means the browser needs no projection code and a site's pin is
positioned by the same two lines as the coastline. Areas near the poles are stretched;
this is a status map and nobody is measuring Greenland.

# Precision

Coordinates are rounded to one decimal place — about 11 km at the equator — and points
that collapse onto their predecessor are dropped. At the size this renders, a tenth of a
degree is well under a pixel.
"""

import io
import json
import sys


def ring_to_path(ring, precision=1):
    """One closed ring as `M x y L x y ... Z`, or None if it collapses."""
    out = []
    last = None
    for lon, lat in ring:
        # Equirectangular into a 360x180 box with the origin at the top left, which is
        # where SVG's origin is. Longitude +180 shifts -180..180 into 0..360; latitude is
        # flipped because SVG's y grows downward and latitude grows upward.
        x = round(lon + 180.0, precision)
        y = round(90.0 - lat, precision)
        point = (x, y)
        if point == last:
            continue
        out.append(point)
        last = point

    # Two points is a line and three is the minimum for an area. Below that the ring has
    # been rounded out of existence, which at this precision happens to a few islets.
    if len(out) < 3:
        return None

    def fmt(v):
        # Trailing ".0" on every other number is a third of the file for no information.
        return str(int(v)) if v == int(v) else str(v)

    head = out[0]
    body = " ".join(f"{fmt(x)} {fmt(y)}" for x, y in out[1:])
    return f"M{fmt(head[0])} {fmt(head[1])}L{body}Z"


def main():
    src, out = sys.argv[1], sys.argv[2]
    data = json.load(io.open(src, encoding="utf-8"))

    paths = []
    for feature in data["features"]:
        geometry = feature["geometry"]
        polygons = (
            geometry["coordinates"]
            if geometry["type"] == "MultiPolygon"
            else [geometry["coordinates"]]
        )
        for polygon in polygons:
            for ring in polygon:
                path = ring_to_path(ring)
                if path:
                    paths.append(path)

    body = "".join(paths)
    with io.open(out, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(
            "// Generated by scripts/worldmap.py from Natural Earth's 110m land outline.\n"
            "// Do not edit by hand; regenerate instead.\n"
            "//\n"
            "// Natural Earth is in the public domain: <https://www.naturalearthdata.com/>\n"
            "// states no permission is needed to use it and no credit is required.\n"
            "//\n"
            "// One SVG path in a 360x180 viewBox, equirectangular. A longitude/latitude\n"
            "// pair becomes a point with `x = lon + 180` and `y = 90 - lat`, which is the\n"
            "// same arithmetic the site pins use -- see map.tsx.\n"
            "export const WORLD_LAND ="
        )
        handle.write(f'\n  "{body}";\n')

    print(f"{out}: {len(paths)} rings, {len(body)} characters")


if __name__ == "__main__":
    raise SystemExit(main())
