//! The telemetry envelope — SPEC §M0.3.
//!
//! One shape for every signal. Metrics, logs, traces, flows, events and state
//! transitions all arrive wrapped in this, which is what lets the pipeline resolve
//! identity, normalise and enrich in one place rather than six.
//!
//! `resource_id` is `Option` because **resolution happens in the pipeline, not in the
//! collector** (SPEC §M0.2). Collectors emit what they observed and let the resolver
//! decide who it was.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::attr::AttrMap;
use crate::identity::ObservedIdentity;
use crate::ids::{ResourceId, SiteId, TenantId};

/// Syslog-derived severity, used across all signals.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Severity {
    Trace = 1,
    Debug = 2,
    Info = 3,
    Notice = 4,
    Warn = 5,
    Error = 6,
    Critical = 7,
    Alert = 8,
    Emergency = 9,
}

impl Severity {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Trace => "trace",
            Self::Debug => "debug",
            Self::Info => "info",
            Self::Notice => "notice",
            Self::Warn => "warn",
            Self::Error => "error",
            Self::Critical => "critical",
            Self::Alert => "alert",
            Self::Emergency => "emergency",
        }
    }

    /// Map an RFC 5424 numeric severity (0–7) onto ours.
    ///
    /// Note the inversion: syslog counts *down* from 0 = emergency, which is the
    /// opposite of every other severity scale and a reliable source of bugs.
    #[must_use]
    pub const fn from_syslog(level: u8) -> Self {
        match level {
            0 => Self::Emergency,
            1 => Self::Alert,
            2 => Self::Critical,
            3 => Self::Error,
            4 => Self::Warn,
            5 => Self::Notice,
            7 => Self::Debug,
            _ => Self::Info, // 6, and anything out of range
        }
    }
}

/// Which collector produced this.
///
/// `Hash` because it is one token of a bus subject, and subjects are map keys.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SourceKind {
    Snmp,
    SnmpTrap,
    Syslog,
    Otlp,
    Icmp,
    Tcp,
    Flow,
    /// Generated by the platform itself (alert state changes, audit events).
    Internal,
}

impl SourceKind {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Snmp => "snmp",
            Self::SnmpTrap => "snmp_trap",
            Self::Syslog => "syslog",
            Self::Otlp => "otlp",
            Self::Icmp => "icmp",
            Self::Tcp => "tcp",
            Self::Flow => "flow",
            Self::Internal => "internal",
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Source {
    pub kind: SourceKind,
    pub vendor: Option<String>,
    /// Which collector instance — matters once collectors are distributed.
    pub collector_id: String,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MetricKind {
    Gauge,
    /// Stored raw. Rates are computed at query time — storing pre-computed rates
    /// makes re-interpretation impossible, and counter wraps unrecoverable.
    Counter,
    Histogram,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct MetricPoint {
    pub name: String,
    pub value: f64,
    pub unit: Option<String>,
    pub kind: MetricKind,
    pub labels: AttrMap,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct LogRecord {
    pub body: String,
    pub facility: Option<u8>,
    pub trace_id: Option<String>,
    pub span_id: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct EventRecord {
    pub category: String,
    pub event_type: String,
    pub summary: String,
    pub details: AttrMap,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StateRecord {
    pub previous: crate::resource::ResourceStatus,
    pub current: crate::resource::ResourceStatus,
    pub reason: String,
}

/// The signal payload. `Trace` and `Flow` are declared now and unimplemented until
/// M8/M7 — declaring them costs an hour and forces the envelope and Query AST to stay
/// general enough that adding them later is additive rather than a redesign.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "signal_type", rename_all = "snake_case")]
pub enum Signal {
    Metric(MetricPoint),
    Log(LogRecord),
    Event(EventRecord),
    State(StateRecord),
    /// M8.
    Trace(serde_json::Value),
    /// M7.
    Flow(serde_json::Value),
}

impl Signal {
    /// Discriminant, for routing and for the `signal_type` column.
    #[must_use]
    pub const fn kind(&self) -> &'static str {
        match self {
            Self::Metric(_) => "metric",
            Self::Log(_) => "log",
            Self::Event(_) => "event",
            Self::State(_) => "state",
            Self::Trace(_) => "trace",
            Self::Flow(_) => "flow",
        }
    }
}

/// One piece of telemetry, from any source, in the one shape the pipeline understands.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TelemetryEnvelope {
    pub tenant_id: TenantId,
    pub site_id: Option<SiteId>,
    /// `None` until the pipeline's identity resolver fills it in.
    pub resource_id: Option<ResourceId>,
    /// What the collector observed about who sent this. Consumed by the resolver.
    pub identity: Option<ObservedIdentity>,

    /// When the source says it happened.
    pub observed_at: DateTime<Utc>,
    /// When we received it. Both are required: the difference is ingest lag, and
    /// without it there is no way to tell a quiet network from a broken collector.
    pub ingested_at: DateTime<Utc>,

    pub source: Source,
    pub severity: Option<Severity>,
    pub attributes: AttrMap,
    pub signal: Signal,
}

impl TelemetryEnvelope {
    /// Ingest lag. Negative values are possible and meaningful — they indicate clock
    /// skew on the sending device, which is worth surfacing rather than clamping.
    #[must_use]
    pub fn lag(&self) -> chrono::Duration {
        self.ingested_at - self.observed_at
    }

    /// Whether identity resolution still has to run for this envelope.
    #[must_use]
    pub const fn is_unresolved(&self) -> bool {
        self.resource_id.is_none()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::identity::IdentifierKind;

    fn envelope() -> TelemetryEnvelope {
        let t0 = Utc::now();
        TelemetryEnvelope {
            tenant_id: TenantId::new(),
            site_id: None,
            resource_id: None,
            identity: Some(
                ObservedIdentity::new("syslog").with(IdentifierKind::Hostname, "rtr-01"),
            ),
            observed_at: t0,
            ingested_at: t0 + chrono::Duration::milliseconds(250),
            source: Source {
                kind: SourceKind::Syslog,
                vendor: Some("cisco".into()),
                collector_id: "collector-1".into(),
            },
            severity: Some(Severity::Error),
            attributes: AttrMap::new(),
            signal: Signal::Log(LogRecord {
                body: "%LINK-3-UPDOWN: Interface Gi0/1, changed state to down".into(),
                facility: Some(23),
                trace_id: None,
                span_id: None,
            }),
        }
    }

    #[test]
    fn syslog_severity_inversion_is_handled() {
        // RFC 5424 counts DOWN from 0 = emergency, opposite to every other scale.
        // Getting this backwards would make debug messages page people.
        assert_eq!(Severity::from_syslog(0), Severity::Emergency);
        assert_eq!(Severity::from_syslog(3), Severity::Error);
        assert_eq!(Severity::from_syslog(6), Severity::Info);
        assert_eq!(Severity::from_syslog(7), Severity::Debug);
        // Out-of-range input must not panic; syslog senders emit nonsense routinely.
        assert_eq!(Severity::from_syslog(200), Severity::Info);
    }

    #[test]
    fn severity_ordering_matches_urgency() {
        assert!(Severity::Emergency > Severity::Error);
        assert!(Severity::Error > Severity::Info);
    }

    #[test]
    fn envelope_starts_unresolved_and_reports_lag() {
        let e = envelope();
        assert!(e.is_unresolved());
        assert_eq!(e.lag().num_milliseconds(), 250);
        assert!(e.identity.is_some(), "collector must pass identity through");
    }

    #[test]
    fn clock_skew_produces_negative_lag_rather_than_being_hidden() {
        let mut e = envelope();
        e.observed_at = e.ingested_at + chrono::Duration::seconds(30);
        assert!(
            e.lag().num_seconds() < 0,
            "device clock skew must stay visible, not be clamped to zero"
        );
    }

    #[test]
    fn signal_round_trips_with_its_discriminant() {
        let e = envelope();
        assert_eq!(e.signal.kind(), "log");
        let json = serde_json::to_string(&e).unwrap();
        assert!(
            json.contains(r#""signal_type":"log""#),
            "signal_type must be on the wire for routing: {json}"
        );
        let back: TelemetryEnvelope = serde_json::from_str(&json).unwrap();
        assert_eq!(back.signal.kind(), "log");
        assert_eq!(back.lag(), e.lag());
    }
}
